---
title: "COVID-19-analysis"
author: "Hubert Krzyżanowski"
date: "12 11 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(dplyr)
library(tidyr)
library(readxl)
library(lubridate)
library(ggplot2)
library(kableExtra)
library(plotly)
library(gganimate)
library(purrr)
```

```{r data_reading}
org_df <- read_excel("wuhan_blood_sample_data_Jan_Feb_2020.xlsx")

```

<!--fill(PATIENT_ID) %>%-->

```{r cleaning_id}
df <- org_df %>% 
        mutate(gender = as.factor(ifelse(gender==1, "male", "female"))) %>%
        mutate(outcome = as.factor(ifelse(outcome == 0, "survived", "died"))) %>%
        rename(admission_time = 'Admission time',
               discharge_time = 'Discharge time')

patients <- df %>% 
              select(PATIENT_ID, age, gender, admission_time, discharge_time, outcome) %>% 
              drop_na(PATIENT_ID) %>%
              mutate("hospitalization_length" = round((difftime(discharge_time, admission_time, units = "days") ), digits = 2)) %>%
              relocate(hospitalization_length, .after = discharge_time)

head(patients) %>%
  kbl() %>%
  kable_paper("hover")
```

```{r patients_plot_gender}
ggplot(patients, aes(x = gender, fill = gender)) +
  geom_bar() + 
  labs(title= "Numer of patients per gender hospitilized in Tongji Hospital (Wuhan) ", 
       subtitle = "between 10 January and 18 February 2020",
       y = "Number of patients", 
       x = "Gender")
```

```{r patients_plot_hist, fig.width= 10}
patients_hist <- ggplot(patients, aes(x = age, fill = gender)) +
  geom_histogram(stat = "count",
                 binwidth = 1.2)+
  labs(y = "Number of patients", 
       x = "Age") +
  scale_x_continuous(breaks=seq(20, 100, 5))
 
ggplotly(patients_hist)      

```


### Outcome grouped by gender, age

```{r out_per_gender_plot, fig.width= 10}

patients_outcome <- ggplot(patients, aes(x = age, fill = outcome)) + 
                    geom_histogram(binwidth = 1.2) +
                    facet_grid(~ gender) +
                    scale_y_continuous(breaks=seq(0, 20, 2)) +
                    scale_x_continuous(breaks=seq(20, 100, 5)) + ylab("Number of cases")

ggplotly(patients_outcome)
```

### Outcome due to hospitalization length grouped by gender
```{r fig.width= 9}

ggplot(patients, aes(x = hospitalization_length, fill = outcome)) + 
      geom_histogram(binwidth = 1.2) +
      facet_grid(outcome ~ gender) +
      scale_y_continuous(breaks=seq(0, 20, 2)) +
      scale_x_continuous(breaks=seq(0, 40, 5)) +
      labs(y = "Number of patients", 
           x = "Hospitalization length [days]")

```

### Outcome animation over time
```{r fig.width= 9}


```